package top.defaults.camera;

public enum CameraStatusCode {
    CAMERA_INIT_ERROR(1000),

    CAMERA_DEINIT_ERROR(1010),

    CAMERA_ALREADY_STARTED(1020),

    CAMERA_INIT_SUCCESS(1030),

    CAMERA_PREVIEW_NOT_INIT(1040),

    CAMERA_PREVIEW_INIT(1050),

    CAMERA_START_NO(1051),

    CAMERA_START_FAILED(1060),

    CAMERA_STOP_SUCCESS(1070),

    CAMERA_STOP_FAILED(1080),

    CAMERA_CONFIG_ERROR(1090),

    CAMERA_PROCESS_LISTENER_ATTACHED(1100),

    CAMERA_DISPLAY_LISTENER_ATTACHED(1110),

    CAMERA_DISPLAY_LISTENER_DETACHED(1120),

    CAMERA_PROCESS_LISTENER_DETACHED(1130),

    CAMERA_IR_ON(1140),

    CAMERA_IR_OFF(1150),

    CAMERA_DEINIT_SUCCESS(1160),

    CAMERA_IR_FAILED(1170),

    CAMERA_IR_SUCCESS(1180),

    DISPLAY_PAUSED_TO_UI_SUCCESS(1181),

    DISPLAY_PAUSED_TO_UI_FAILED(1182),

    CAMERA_CALLBACK_REGISTRATION_SUCCESS(1183),

    CAMERA_CALLBACK_REGISTRATION_FAILED(1184);


    private int statusCode;

    private CameraStatusCode(int statusCode) {
        this.statusCode = statusCode;
    }


    public int getStatusCode() {
        return statusCode;
    }
}
